### ISSUE TITLE
关于predict的问题

### ISSUE THREAD

**Issue by xklg309** [SeanLee97/QANet_dureader#3]
训练一切正常，包括训练期间dev数据集的验证也都能查看到正确的ROUGE评分，最终执行predict却报错，
这是我的执行参数
python cli.py --predict --batch_size 16 --learning_ra
te 1e-2 --weight_decay 0.9999 --max_norm_grad 5.0 --dropout 0.9 --head_size 1 --hidden_size 128 --epochs 50 --gpu=
报错如下
Traceback (most recent call last):
  File "cli.py", line 299, in <module>
    run()
  File "cli.py", line 296, in run
    predict(args)
  File "cli.py", line 257, in predict
    model.restore(model_dir=args.model_dir)
TypeError: restore() missing 1 required positional argument: 'model_prefix'

我没有找到model_prefix这个参数的选项，请问该如何处理

**Comment by SeanLee97** [comment]
@xklg309 已修复，改进处：
1. [cli.py / 217](https://github.com/SeanLee97/QANet_dureader/blob/master/cli.py#L217)
2. [cli.py / 249](https://github.com/SeanLee97/QANet_dureader/blob/master/cli.py#L249)

**Comment by xklg309** [comment]
已经可以完整运行了，还有2处错误望您修改
1.还缺少这个参数pad_char_id，我自行修改了2处
2.predict.sh 中的参数--clip_weight需要删除，--hidden_size 128改为64，需要对应train.sh的参数修改

Traceback (most recent call last):
  File "cli.py", line 303, in <module>
    run()
  File "cli.py", line 300, in run
    predict(args)
  File "cli.py", line 264, in predict
    pad_id=vocab.get_word_id(vocab.pad_token), shuffle=False)
TypeError: next_batch() missing 1 required positional argument: 'pad_char_id'

**Comment by tomtang110** [comment]
请问下，我在demo上面还能够正常运行，但是运行大数据的时候，发现loss突然之间变得超级大，请问怎么办呢？
